# Server Configuration
server:
  port: 8080
  
spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      routes:
        - id: PRODUCT-SERVICE
          uri: lb://PRODUCT-SERVICE
          predicates:
            - Path=/api/v1/product-service/**
  
# Eureka Configuration
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  
# Logging Configuration
logging:
  level:
    root: INFO
    org.springframework.cloud.gateway.handler.RoutePredicateHandlerMapping: DEBUG